### ISSUE TITLE
 Setting up the skeleton backend

### ISSUE THREAD

**Issue by msypniewski511** [msypniewski511/MERN-BACKBONE#7]
### Tasks
  - [x] set up the project folder
  - [x] install and configure the necessary Node modules
  - [x] prepare run scripts to aid development and run the code
  - [x] implement a working Express server
  - [x] setup Mongoose
  - [x] Serving an HTML template at a root URL

**Comment by msypniewski511** [comment]
Forgotten all config
